---

  - name: Copy docker-compose file to host
    template: 
      src: docker-compose.yml.j2
      dest: /tmp/docker-compose.yml

  - name: Run docker docker-compose    
    command: chdir=/tmp/  docker-compose up
    
  - name: Initialize a git repository
    command: chdir=/tmp/repo-to-copy/semaphore/playbooks/ git init .

  - name: Setup git username
    command: git config --global user.name "semaphore"  
 
  - name: Add all to git repository
    command: chdir=/tmp/repo-to-copy/semaphore/playbooks/ git add .

  - name: Commit all files
    command: chdir=/tmp/repo-to-copy/semaphore/playbooks/ git commit -m "add all files"    

  - name: Append repository json text to config.json
    shell: python /tmp/semaphore_setup/semaphore_setup/scripts/fix_config.py  /tmp/repo-to-copy/semaphore/config/config.json > /tmp/repo-to-copy/semaphore/config/new_config.json

  - name: Import Playbooks json
    shell: python /tmp/semaphore_setup/semaphore_setup/semaphore_api_call/main.py  --username {{ semaphore_username }} --password {{ semaphore_password }} --host   {{ semaphore_url }} --project-file /tmp/repo-to-copy/semaphore/config/new_config.json
    